cast/urls.py
# -*- coding: utf-8 -*-

from django.urls import path

from cast.views import (
    SearchView, PodcastDetailView, PodcastAboutView,
    PodcastMonthArchiveView, uplike
    )
    
from cast.models import Podcast

app_name = 'cast'

urlpatterns = [
    path('search/', SearchView.as_view(), name='search'),
    path('p/<slug>/<pk>/', PodcastDetailView.as_view(), name='podcast'),
    path('p/<slug:slug>/<int:podcast_id>/like/', uplike, name='uplike'),
    path('p/archive/<str:month>/<int:year>/', PodcastMonthArchiveView.as_view(), name='archive_month'),
    path('about/', PodcastAboutView.as_view(), name='about'),
]

podcast/urls.py
"""podcast URL Configuration
"""

from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from cast.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('', include("cast.urls", namespace='cast')),
    path('axb/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cast/models.py
# cats/models.py

__author__ = 'Flavien-hugs <flavienhugs@pm.me>'
__version__= '0.0.1'
__copyright__ = '© 2019'

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.core.files.storage import default_storage

# Create your models here.

# MODEL CATEGORIE
class Categorie(models.Model):
    CATEGORIES_CHOICES = (
        ('showbiz', 'Showbiz'),
        ('evenement', 'Evenement'),
        ('culture', 'Culture'),
        ('music', 'Music'),
        ('documentaire', 'Documentaire'),
        ('formation', 'Formation'),
        ('interview', 'Interview'),
        ('reportage', 'Reportage'),
    )
    cat = models.CharField('Categorie', max_length=50, choices=CATEGORIES_CHOICES, default='showbiz')
    slug = models.SlugField('Référence', max_length=50, unique=True, help_text='Automatiquement formé à partir du titre.')

    class Meta:
        verbose_name = 'catégorie'
        verbose_name_plural = 'catégories'
        ordering = ('cat',)

    def __str__(self):
        return self.cat

    def get_absolute_url(self):
        return reverse('cast:cat_listing', kwargs={'slug': self.slug})


# MODEL PODCAST
class Podcast(models.Model):
    categorie = models.ManyToManyField(Categorie, verbose_name="Catégorie")
    title = models.CharField('Titre', max_length=100)
    slug = models.SlugField('Url', max_length=100, unique=True, help_text="Automatiquement formé à partir du titre.")
    description = models.TextField('Description')
    image = models.ImageField('Image de description', upload_to="audio/",
        blank=True, null=True, help_text="Dimension d'image recommandé (300x306).")
    url_audio = models.URLField('Url fichier audio', max_length=200)
    publish = models.DateTimeField('Date de publication', default=timezone.now)
    like = models.IntegerField('Nombre de votes', default=0)

    class Meta:
        ordering = ('publish',)
        verbose_name = 'podcast'
        verbose_name_plural = 'podcasts'

    def __str__(self):
        return "%s (%s)" % (
            self.title, ", ".join(categorie.cat for categorie in self.categorie.all()),)

    def get_absolute_url(self):
        return reverse('cast:podcast', kwargs={'slug': self.slug, 'pk': self.id})

    def save(self):
        try:
            img = Podcast.objects.get(pk=self.id)
            path = img.image.path
            if img.image.path != self.small_image.path_1:
                default_storage.delete(path)
            elif self.remove_image:
                self.image = None
                default_storage.delete(path)
        except:
            pass
        self.remove_image = False

        super(Podcast, self).save()

cast/views.py
# -*- coding: utf-8 -*-

from django.urls import reverse
from django.db.models import Q, F
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import View, TemplateView
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.dates import MonthArchiveView
from django.http import HttpResponse, HttpResponseRedirect

from cast.models import Podcast, Categorie


# VUE DE RECHERCHE
class SearchView(View):

    def get(self, request):
        queryset = Podcast.objects.all()
        query = request.GET.get('q')
        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) | Q(description__icontains=query) |
                Q(categorie__cat__icontains=query)).distinct()

        context = {'queryset': queryset}
        template = 'cast/podscat_search.html'

        return render(request, template, context)


# VUE DE LA PAGE D'ACCUEIL
class HomeView(ListView):
    model = Podcast
    template_name = 'index.html'

    def get_queryset(self):
        return Podcast.objects.order_by('publish')[:10]
    
    def head(self):
        latest_podcast = self.get_queryset().latest('publish')
        response = HttpResponse('')
        response['Last-Modified'] = latest_podcast.publish.strftime(
            '%a, %d %b %Y %H:%M:%S GMT')
        return response

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        cat = Categorie.objects.all()
        context['categorie'] = cat

        return context


# VUE DE LA PAGE DE DETAIL
class PodcastDetailView(DetailView):
    model = Podcast
    template_name = 'cast/podcast_detail.html'

    def get_context_data(self, **kwargs):
        context = super(PodcastDetailView, self).get_context_data(**kwargs)
        cat = Categorie.objects.all()
        context['categorie'] = cat

        return context


# VUE DE LA PAGE ABOUT
class PodcastAboutView(TemplateView):
    template_name = 'cast/podcast_about.html'

    def get_context_data(self, **kwargs):
        context = super(PodcastAboutView, self).get_context_data(**kwargs)
        cat = Categorie.objects.all()
        context['categorie'] = cat
        context['title'] = "about".upper()
        return context


# VUE LIKE PODCAST
def uplike(request, slug, podcast_id):
    if request.method == 'POST':
        podcast = get_object_or_404(Podcast, slug=slug, pk=podcast_id)
        podcast.like += 1
        podcast.save()
        return HttpResponseRedirect(reverse('cast:podcast',
                                            args=[podcast.slug, podcast.id]))


# VUE ARCHIVE DU MOIS
class PodcastMonthArchiveView(MonthArchiveView):
    queryset = Podcast.objects.dates('publish', 'month')
    date_field = "publish"
    month_format = '%m'
    year_format = '%Y'
    allow_future = False

templates/cast/podcast_about.html
{# templates/cast/podcast_about.html #}
{% extends "index.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static "css/about.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/about_responsive.css" %}">
{% endblock css %}

{% block content %}
    <!-- presentation -->
    <div class="intro section-about">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="intro-content text-center">
                        <div class="section-title text-center">
                            <h1>Qui sommes-nous ?</h1>
                        </div>

                        <div class="intro-text text-center">
                            <p>
                                Situé en Côte d'Ivoire, dans la région du Gbêkê précisement à Bouaké, Gbêkê Fm est une station de radio qui diffuse sur internet grace à la technologie plutôt que sur les ondes. C'est la première web radio dans la région du Gbéké . Elle existe depuis un an et est spécialisée dans le montage audio visuel, la publicité à travers ses directs, des couvertures médiatiques, diffusion de spot, communiqué en langue, émissions, des formations en techniques radio, journalisme, animation radio, reportage et autre.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end presentation -->

    <!-- milestones -->
    <div class="milestones">
        <div class="parallax-background parallax-window" data-parallax="scroll" data-image-src="{% static "img/milestones.jpg" %}" data-speed="0.8"></div>

        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="section-title light text-center">
                        <h1>Qui nous suit ?</h1>
                    </div>
                </div>
            </div>

            <div class="row milestones-row">
                <div class="col-xl-3 col-md-6">
                    <div class="milestone text-center">
                        <div class="milestone-content ml-auto mr-auto">
                            <div class="milestone-counter" data-end-value="55126">0</div>
                            <div class="milestone-icon"><img src="{% static "img/alarm-clock.svg" %}" alt=""></div>
                        </div>
                        <div class="milestone-title">Streamed Hours</div>
                    </div>
                </div>

                <div class="col-xl-3 col-md-6">
                    <div class="milestone text-center">
                        <div class="milestone-content ml-auto mr-auto">
                            <div class="milestone-counter" data-end-value="3520">0</div>
                            <div class="milestone-icon"><img src="{% static "img/speaker.svg" %}" alt=""></div>
                        </div>
                        <div class="milestone-title">Audio Episodes</div>
                    </div>
                </div>

                <div class="col-xl-3 col-md-6">
                    <div class="milestone text-center">
                        <div class="milestone-content ml-auto mr-auto">
                            <div class="milestone-counter" data-end-value="2056">0</div>
                            <div class="milestone-icon"><img src="{% static "img/film.svg" %}" alt=""></div>
                        </div>
                        <div class="milestone-title">Interviews</div>
                    </div>
                </div>

                <div class="col-xl-3 col-md-6">
                    <div class="milestone text-center">
                        <div class="milestone-content ml-auto mr-auto">
                            <div class="milestone-counter" data-end-value="25">0</div>
                            <div class="milestone-icon"><img src="{% static "img/television.svg" %}" alt=""></div>
                        </div>
                        <div class="milestone-title">Documentaires</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end milestones -->

    <!-- about us -->
    <div class="about">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="about-container d-flex flex-lg-row flex-column align-items-start justify-content-start">
                        <div class="about-content">
                            <div class="section-title"><h1>About Me</h1></div>
                            <div class="about-text">
                                <p>Situé en Côte d'Ivoire, dans la région du Gbêkê précisement à Bouaké, Gbêkê Fm est une station de radio qui diffuse sur internet grace à la technologie plutôt que sur les ondes. C'est la première web radio dans la région du Gbéké . Elle existe depuis un an et est spécialisée dans le montage audio visuel, la publicité à travers ses directs, des couvertures médiatiques, diffusion de spot, communiqué en langue, émissions, des formations en techniques radio, journalisme, animation radio, reportage et autre.</p>
                            </div>
                            <div class="social">
                                <ul class="d-flex flex-row align-items-start justify-content-start">
                                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="about-image"><img src="{% static "img/man.png" %}" alt=""></div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- end about us -->
{% endblock content %}

templates/cast/podcast_archive_month.html
        {# templates/cast/podcast_archive_year.html #}
    
        <div class="dropdown">
            <ul>
                <li class="dropdown-selected d-flex flex-row align-items-center justify-content-start"><span>{{ year }}</span><i class="fa fa-chevron-down ml-auto" aria-hidden="true"></i>
                    <ul>
                        {% if object_list %}
                            {% for obj in object_list %}
                                <li>
                                    <a href="#">
                                        {{ obj.publish|date:"F Y" }}
                                    </a>
                                </li>
                            {% endfor %}
                        {% elif object %}
                            <li>
                                <a href="#">
                                    {{ object.publish|date:"F Y" }}
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>

templates/cast/podcast_detail.html
{# templates/cast/podcast_about.html #}
{% extends "index.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static "css/detail.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/detail_responsive.css" %}">
{% endblock css %}

<!-- Home -->
{% block home %}
    <div class="home">
        <div class="parallax-background parallax-window" data-parallax="scroll" data-image-src="{% static "img/episode.jpg" %}" data-speed="0.8"></div>
        <div class="home-container">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="home-content text-center">
                            <div class="home-title text-white">
                                <h1> {{ object.title|upper|safe }} </h1>
                            </div>
                            <div class="home-subtitle text-center">
                                {{ object.publish|date }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="home-player-container">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9 offset-lg-3">
                        <!-- episode -->
                        <div class="player d-flex flex-row align-items-start justify-content-start">
                            <div class="player-content">
                                <!-- player -->
                                <div class="single-player-container">
                                    <div class="single-player flex-row align-items-center justify-content-start">
                                        <div class="player">
                                            <audio id="player1" preload="none" controls style="width:100%">
                                                <source src="{{ object.url_audio }}" type="audio/mp3">
                                            </audio>
                                        </div>
                                    </div>
                                </div>

                                <div class="show-info d-flex flex-row align-items-start justify-content-start">
                                    <div class="show-comments">
                                        <a href="javascript:{document.getElementById('uplike{{ object.id }}').submit()}">
                                            <div class="d-flex flex-row align-items-center justify-content-start">
                                                <div class="show-comments-icon show-info-icon"><img class="svg" src="{% static "img/heart.svg" %}"></div>
                                                <div class="show-comments-count">{{object.like}} like{{ object.like|pluralize }}</div>
                                            </div>
                                        </a>    
                                    </div>
                                </div>
                                <form action="{% url 'cast:uplike' object.slug object.id %}" method="POST" id="uplike{{ object.id }}">{% csrf_token %}<input type="hidden"></form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock home %}<!-- .end/ Home -->

{% block content %}
    <div class="episode-container">

        <!-- Episode Image -->
        <div class="episode-image-container">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <!-- Episode Image -->
                        <div class="episode-image">
                            <img src="{% if object.image %}{{ object.image.url }}{% else %}{% static "img/gbekefm.jpg" %}{% endif %}" alt="{{ object.title }}">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                
                <!-- sidebar -->
                <div class="col-lg-3 order-lg-1 order-2 sidebar-col">
                    <div class="sidebar">
                        {% include "includes/sidebar.html" %}
                    </div>
                </div><!-- end sidebar -->

                <!-- emission -->
                <div class="col-lg-9 episode-col order-lg-2 order-1">
                    <div class="intro">
                        <div class="section-title">
                            {% for c in object.categorie.all %}
                                {{ c.cat|upper|safe }}
                            {% endfor %} &smid; {{ object.title|safe }}
                        </div>
                         
                        <div class="intro-text">
                            <p>{{ object.description }}</p>
                        </div>
                    </div>
                    <div class="guests">
                        <div class="section-title">Invité du jours</div>
                        <div class="guests-container d-flex flex-md-row flex-column align-items-md-start align-items-center justify-content-start">
                            
                            <!-- invités -->
                            <div class="guest-container">
                                <div class="guest">
                                    <div class="guest-image"><img src="{% static "img/gbekefm.jpg" %}" alt=""></div>
                                    <div class="guest-content text-center">
                                        <div class="guest-name"><a href="#">
                                            Mr Kobenan
                                        </a></div>
                                        <div class="guest-title">DG de Gbêke Fm</div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                    <!-- commentaire -->

                    <!-- ajouter un commentaire -->
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/cast/podcast_latest.html
        {# templates/cast/podcast-latest.html #}
    
        {% load static tags %}

        <!-- Latest -->
        {% for las in latest %}
            <div class="latest">
                <div class="latest-title-container d-flex flex-row align-items-start justify-content-start">
                    <a href="{{ las.get_absolute_url }}">
                        <div class="d-flex flex-row align-items-start justify-content-start">
                            <div class="latest-play">
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa-1" x="0px" y="0px" width="512px" height="512px" viewBox="0 0 714 714" style="enable-background:new 0 0 714 714;" xml:space="preserve">
                                    <g id="Play">
                                        <path d="M641.045,318.521L102,0C73.822,0,51,22.822,51,51v612c0,28.178,22.822,51,51,51l539.045-318.521      C654.661,387.422,663,372.81,663,357C663,341.19,654.661,326.579,641.045,318.521z M153,565.386V148.614L505.665,357      L153,565.386z" fill="#FFFFFF"/>
                                    </g>
                                </svg>
                            </div>

                            <div class="latest-title-content">
                                <div class="latest-title">{{ las.title|truncatewords:6|safe }}</div>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="latest-episode-info">
                    <ul class="d-flex flex-row align-items-start justify-content-start">
                        <li><a href="{{ las.get_absolute_url }}">{{ las.publish|date }}</a></li>
                        <li><a href="#">
                            {% for c in las.categorie.all %}
                                {{ c.cat|upper|safe }}
                            {% endfor %}
                        </a></li>
                    </ul>
                </div>
            </div>
        {% endfor %}

templates/includes/pagination.html
    {# templates/includes/pagination.html #}
    
    
        <div class="row page-nav-row">
            <div class="col">
                <div class="page-nav d-flex flex-row align-items-center justify-content-center">
                    <ul class="d-flex flex-row">
                        <li class="active"><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#"><i class="fa fa-angle-double-right" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    

templates/index.html
{# templates/home.html #}
<!doctype html>
<html lang="fr">
  <head>
    {% load static tags %}
    
    {# INSERTION META FILE #}
    {% include "includes/meta.html" %}

    {# CUSTOM CSS #}
    {% block css %}
      <link rel="stylesheet" type="text/css" href="{% static "css/custom.css" %}">
      <link rel="stylesheet" type="text/css" href="{% static "css/custom_responsive.css" %}">
    {% endblock css %}
    
    <title>
      {% block title %}
        {% if title %}
          {{ title }}
        {% elif object.title %}
          {{ object.title }}
        {% else %}
          {{ site_description }}
        {% endif %}
        &smid; {{ site_name }}
      {% endblock title %}
    </title>

    <!--[if IE 7]><body class="ie7 lt-ie8 lt-ie9 lt-ie10"><![endif]-->
    <!--[if IE 8]><body class="ie8 lt-ie9 lt-ie10"><![endif]-->
    <!--[if IE 9]><body class="ie9 lt-ie10"><![endif]-->
  </head>

  <body class="d-flex flex-column">
    <div class="flex-grow-1 flex-shrink-0">
      <div class="super-container">
        <!-- Header -->
        <header class="header trans-400">
          <!-- Logo -->
          <div class="logo">
            <a href="/"><span>Gbêkế</span>Fm</a>
          </div><!-- end logo -->

          <div class="container">
            <div class="row">
              <div class="col">
                <div class="header-content d-flex flex-row align-items-center justify-content-start trans-400">
                  <nav class="main-nav">
                    <ul class="d-flex flex-row align-items-start justify-content-start">
                      <li><a href="/">Home</a></li>
                      <li><a href="{% url "cast:about" %}">About</a></li>
                    </ul>
                  </nav>
                </div>
              </div>
            </div>
          </div>

          <!-- social -->
          <div class="header-right d-flex flex-row align-items-start justify-content-start">
            <div class="submit">
              <script src="{% static "js/cinetpay-button.js" %}?apikey=174323661757617531bf99c9.80613927"
                data-button="donate"
                data-designation="Soutenir la radio"
                data-amount="25"
                data-trans-id="8575421"
                data-payment-config="SINGLE"
                data-page-action="PAYMENT"
                data-version="V2"
                data-currency="CFA"
                data-language="fr"
                data-custom=""
                data-site-id="393509"
                data-golive="no"
                data-callback="{% url "home" %}notify/"
                data-return-page="{% url "home" %}return/"
                data-cancel-page="{% url "home" %}cancel/"
                async>
              </script>
            </div>
      
            <div class="social">
              <ul class="d-flex flex-row align-items-start justify-content-start">
                <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
              </ul>
            </div>

            <!-- Hamburger -->
            <div class="hamburger">
              <i class="fa fa-bars" aria-hidden="true"></i>
            </div><!-- end Hamburger -->
          </div><!-- end social -->
        </header><!-- ./end Header -->

        <!-- Menu -->
        <menu class="menu">
          <div class="menu-content d-flex flex-column align-items-end justify-content-start">
            <ul class="menu-nav-list text-right">
              <li><a href="/">Home</a></li>
              <li><a href="{% url "cast:about" %}">About</a></li>
            </ul>
            <div class="menu-extra d-flex flex-column align-items-end justify-content-start">
              <div class="social">
                <ul class="d-flex flex-row align-items-start justify-content-start">
                  <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </menu><!-- ./end Menu -->

        <!-- Home -->
        {% block home %}
          <div class="home">
            <div class="parallax-background parallax-window" data-parallax="scroll" data-image-src="{% static "img/about.jpg" %}" data-speed="0.8">
            </div>
          </div>
        {% endblock home %}<!-- .end/ Home -->

        {% block content %}
          <!-- episodes -->
          <main class="episodes section-podcast">
            <div class="container">
              <div class="row">
                <!-- sidebar -->
                <aside class="col-lg-3">
                  <div class="sidebar">
                    <!-- Search -->
                    <div class="sidebar-search">
                      <div class="sidebar-title">Search</div>
                      <form action="#" class="search-form" id="search-form">
                        <input type="text" class="search-input" placeholder="Search here" required="required">
                        <button class="search-button">
                          <i class="fa fa-search"></i>
                        </button>
                      </form>
                    </div><!-- end Search -->

                    {# INSERTION SIDEBAR FILE #}
                    {% include "includes/sidebar.html" %}
                  </div>
                </aside><!-- end Sidebar -->

                <!-- all podcast -->
                <section class="col-lg-9 episodes-col">
                  <div class="episodes-container">
                    
                    <!-- podscat -->
                    {% for obj in object_list %}
                      <div class="episode d-flex flex-row align-items-start justify-content-start s1">
                        <!-- image podscat -->
                        <div>
                          <div class="episode-image">
                            <img src="{% if obj.image %}
                              {{ obj.image.url }} {% else %} {% static "img/gbekefm.jpg" %} {% endif %}" alt="{{ obj.title }}">
                          </div>
                        </div><!-- end image podscat -->

                        <!-- podscat content -->
                        <div class="episode-content">
                          <div class="episode-name">
                            {% for c in obj.categorie.all %}
                              <a href="{{ obj.get_absolute_url }}">
                                {{ c.cat|upper|safe }} &smid; {{ obj.title|safe }}
                              </a>
                            {% endfor %} 
                          </div>

                          <div class="episode-date">
                            <a href="#"> {{ obj.publish|date }} </a>
                          </div>

                          <div class="show-info d-flex flex-row align-items-start justify-content-start">
                            <div class="show-fav d-flex flex-row align-items-center justify-content-start">
                              <div class="show-fav-icon show-info-icon"><img class="svg" src="{% static "img/heart.svg" %}"></div>
                              <div class="show-fav-count">{{obj.like}} like{{ obj.like|pluralize }}</div>
                            </div>
                          </div>

                          <!-- player -->
                          <div class="single-player-container">
                            <div class="single-player flex-row align-items-center justify-content-start">
                              <div class="player">
                                <audio id="player{{ obj.id }}" preload="none" controls style="width:100%">
                                  <source src="{{ obj.url_audio }}" type="audio/mp3">
                                </audio>
                              </div>
                            </div>
                          </div><!-- end player -->
                        </div><!-- end podscat content -->
                      </div><!-- ./end podscat -->
                    {% endfor %}

                  </div>
                </section><!-- ./end all podcast -->
              </div>
              
              <!-- pagination -->
              {% include "includes/pagination.html" %}
              <!-- end pagination -->
            </div>
          </main><!-- end Episodes -->
        {% endblock content %}
        
      </div>
    </div>
    
    {# INSERTION FOOTER FILE #}
    {% include "includes/footer.html" %}
    
    {# INSERTION JAVASCRIPT FILE #}
    {% include "includes/script.html" %}
  </body>
</html>